# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS4518 Mobile & Ubiqiutous Computing
email: tian@wpi.edu
description: > # this means to ignore newlines until "baseurl:"
  Course description
school: Worcester Polytechnic Institute

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wpimobile18b.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  wpimobile18b

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

header_pages:
  - syllabus.md

# code highlight with rouge: https://sacha.me/articles/jekyll-rouge/
highlighter: rouge

kramdown:
  input: GFM
#kramdown:
#  input: GFM
  hard_wrap: true
  parse_block_html: true # needed to allow markdown inside <div> tags


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - notes.md
   - styles/
   - projects/
   - readings/
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
